[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0B7285"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#E9ECEF"
textColor = "#212529"
font = "sans serif"
